import type { Metadata } from "next";
import Link from "next/link";
import { EvidenceStatusBadge } from "@/components/evidence-status-badge";
import { SiteHeader } from "@/components/site-header";
import { radiologicalDocuments } from "@/data/radiological-investigation";

export const metadata: Metadata = { title: "Southtowns and Buffalo Slag investigation", description: "Evidence connecting Abbott Road, Republic Steel TENORM, Buffalo Slag, and Southtown construction-material markets.", alternates: { canonical: "/research/radiological/southtowns-slag" } };
const ids = ["abbott-road-slag-assessment-2025", "riverbend-tenorm-2016", "hamburg-no-slag-1989", "buffalo-slag-steelawanna-1988", "hanna-furnace-slag-distribution-1988", "boston-buffalo-slag-bid-1983", "nysdec-tenorm-policy-2023"];
export default function SouthtownsSlagPage() { const records = ids.map((id) => radiologicalDocuments.find((record) => record.id === id)).filter(Boolean); return <main className="index-page"><SiteHeader /><article className="radiological-subpage"><Link href="/research/radiological-industry-fill">← Radiological investigation hub</Link><header><EvidenceStatusBadge status="research-in-progress" /><p className="eyebrow">Southtowns slag investigation</p><h1>Industrial slag is a testable lead—not a proven explanation.</h1><p>Government records connect Buffalo-area iron and steel slag to TENORM, a historical processor, construction markets, and surviving Southtown infrastructure. They do not yet connect those facts into one proven radiological delivery route.</p></header><aside className="school-caution"><strong>The investigation question</strong><p>Are current Southtown radiological areas of interest occurring where historical industrial slag was placed? Public property-level coordinates, laboratory results, construction records, and delivery records are still needed.</p></aside><section><h2>The documented chain</h2>{records.map((record) => record && <article className="subpage-evidence-record" key={record.id}><time>{record.date}</time><h3>{record.title}</h3><p>{record.establishes}</p><p><strong>Limit:</strong> {record.mapConnection}</p><a href={record.url} target="_blank" rel="noreferrer">Open source record ↗</a></article>)}</section></article></main>; }
